# Generated by Django 6.1 on 2026-08-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='trainers/')),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('specialty', models.CharField(help_text='e.g. Strength Training, Yoga, Weight Loss', max_length=150)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('training_categories', models.CharField(blank=True, help_text='Comma-separated, e.g. Weight Training, Yoga, Cardio', max_length=255)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
