# Generated by Django 6.1 on 2026-08-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
