# Generated by Django 6.1 on 2026-08-15 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_trainer_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GymClass',
        ),
    ]
