# Generated by Django 6.1 on 2026-08-15 14:39

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_delete_gymclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        # Renamed (not dropped/recreated) so any enquiries already submitted by
        # real site visitors on the live deployment are preserved, not deleted.
        migrations.RenameModel(old_name='ContactMessage', new_name='Enquiry'),
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Enquiries'},
        ),
        migrations.AddField(
            model_name='enquiry',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', validators=[website.models.validate_image_size])),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('gym', 'Gym'), ('equipment', 'Equipment'), ('trainers', 'Trainers'), ('training', 'Training'), ('events', 'Events'), ('members', 'Members')], default='gym', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('member_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', validators=[website.models.validate_image_size])),
                ('quote', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='1 to 5 stars')),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='RUDRA FITNESS', max_length=100)),
                ('tagline', models.CharField(default='Train Strong. Live Strong.', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/', validators=[website.models.validate_image_size])),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/', validators=[website.models.validate_image_size])),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='branding/', validators=[website.models.validate_image_size])),
                ('home_intro_heading', models.CharField(default='Why choose RUDRA FITNESS?', max_length=200)),
                ('home_intro_text', models.TextField(blank=True, default='Male and female training, professional trainers, modern equipment, personalized plans, flexible memberships, diet guidance and a clean, safe environment.')),
                ('members_count', models.PositiveIntegerField(default=0, help_text='Shown in the homepage stats counter')),
                ('trainers_count', models.PositiveIntegerField(default=0)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('programs_count', models.PositiveIntegerField(default=0)),
                ('phone_primary', models.CharField(blank=True, max_length=20)),
                ('phone_secondary', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('google_maps_embed_url', models.URLField(blank=True)),
                ('opening_hours', models.TextField(blank=True, help_text="One line per day, e.g. 'Mon-Sat: 6:00 AM - 10:00 PM'")),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('privacy_policy', models.TextField(blank=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('todays_motivation', models.CharField(blank=True, max_length=300)),
                ('workout_of_the_day', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Settings',
                'verbose_name_plural': 'Website Settings',
            },
        ),
        migrations.DeleteModel(
            name='MembershipPlan',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
