# Generated by Django 6.1 on 2026-08-15 14:54

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_seed_website_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength Machines'), ('free_weights', 'Free Weights'), ('functional', 'Functional Training')], default='strength', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment/', validators=[website.models.validate_image_size])),
                ('is_visible', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Equipment',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
