# Generated by Django 6.1 on 2026-08-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='preferred_training_time',
            field=models.CharField(blank=True, choices=[('', 'No preference'), ('early_morning', 'Early Morning (5 AM - 8 AM)'), ('morning', 'Morning (8 AM - 11 AM)'), ('afternoon', 'Afternoon (11 AM - 4 PM)'), ('evening', 'Evening (4 PM - 7 PM)'), ('night', 'Night (7 PM - 10 PM)')], max_length=20),
        ),
    ]
