# Generated by Django 6.1 on 2026-08-15 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin_notification', models.BooleanField(default=False)),
                ('event_type', models.CharField(choices=[('registration', 'New Registration'), ('payment_success', 'Payment Successful'), ('membership_activated', 'Membership Activated'), ('membership_expiring', 'Membership Expiring Soon'), ('membership_expired', 'Membership Expired'), ('enquiry', 'New Enquiry'), ('announcement', 'Admin Announcement')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, help_text='Leave blank for admin-only notifications', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['is_admin_notification', 'is_read'], name='notificatio_is_admi_226f0b_idx')],
            },
        ),
    ]
