# Generated by Django 6.1 on 2026-08-15 14:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('method', models.CharField(choices=[('qr', 'QR Check-in'), ('manual', 'Manual (Admin)')], default='qr', max_length=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='members.memberprofile')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Admin/staff who recorded a manual entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-check_in_time'],
                'indexes': [models.Index(fields=['member', 'check_in_time'], name='attendance__member__1a4486_idx')],
            },
        ),
    ]
